"use client"
import React from "react";
import { Inter } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "../_app";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "@/constants/themes";
import "@/styles/index.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ChakraProvider theme={theme}>
              {children}
          </ChakraProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
